---
name: Pull Request

on:
  pull_request:
  repository_dispatch:
    types: [apb]

env:
  ENVIRONMENT: dev
  IMAGE_NAME: con-pca-gophish
  REGION: us-east-1
  PIP_CACHE_DIR: ~/.cache/pip
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_BUCKET: con-pca-terraform
  TF_DYNAMO_TABLE: con-pca-tf-lock

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Workspace
        working-directory: ./terraform
        run: |
          terraform workspace select $ENVIRONMENT
          terraform workspace show

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:0:10})

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false -var="image_tag=${{steps.vars.outputs.tag}}" -var-file ./vars/$ENVIRONMENT.tfvars
